{{- if and .Values.redis.auth.managementEndpoints (not .Values.redis.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "steadybit-extension-redis.fullname" . }}-auth
  labels:
    {{- include "steadybit-extension-redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  endpoints-json: {{ .Values.redis.auth.managementEndpoints | toJson | quote }}
{{- end }}
