apiVersion: v2
name: steadybit-extension-redis
description: A Steadybit extension for Redis chaos engineering
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - steadybit
  - redis
  - chaos-engineering
  - extension
home: https://www.steadybit.com
icon: https://steadybit.com/favicon.ico
sources:
  - https://github.com/steadybit/extension-redis
maintainers:
  - name: steadybit
    email: support@steadybit.com
